export enum SocketEvents {
  message = "message",
  sendMessage = "sendMessage",
  deleteMessage = "deleteMessage",
  seenMessage = "seenMessage",
  editMessage = "editMessage",
  replyMessage = "replyMessage",
  online = "online",
  offline = "offline",
  block = "block",
  unBlock = "unBlock",
  startTyping = "startTyping",
  info = "info",
  chatsOnline = "chatsOnline",
}
